### ISSUE TITLE
Transfer project to MVC pattern

### ISSUE THREAD

**Issue by Vlad1enko** [Vlad1enko/ProgrammingTechnologies3rd#1]
### Todo list:

- [x] - Think about new project architecture
- [x] - Create new folders and move files there
- [x] - Divide classes into logic models
- [x] - Add new functions in controller/service files
- [x] - Cover with tests
